version: "3.8"
services:
  flood:
    image: jesec/rtorrent-flood
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    restart: unless-stopped
    command: --port 3001 --allowedpath /downloads
    ports:
      - 3001:3001
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./config/rtorrent:/config
      - downloads:/downloads
    environment:
      - BASEDIR=/config
      - TZ=America/Los_Angeles
  prowlarr:
    restart: unless-stopped
    image: linuxserver/prowlarr
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr:/config
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
  sonarr:
    restart: unless-stopped
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config
      - tv:/tv
      - anime:/anime
      - downloads:/downloads
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
  radarr:
    restart: unless-stopped
    image: linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - movies:/movies
      - downloads:/downloads
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
  lidarr:
    restart: unless-stopped
    image: linuxserver/lidarr
    ports:
      - 8686:8686
    volumes:
      - ./config/lidarr:/config
      - music:/music
      - downloads:/downloads
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
  overseerr:
    restart: unless-stopped
    image: linuxserver/overseerr
    ports:
      - 5055:5055
    volumes:
      - ./config/overseer:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
volumes:
  downloads:
    driver_opts:
      type: nfs
      o: addr=192.168.1.6,vers=4,nolock,soft,rw
      device: :/volume1/downloads
  music:
    driver_opts:
      type: nfs
      o: addr=192.168.1.6,vers=4,nolock,soft,rw
      device: :/volume1/music
  anime:
    driver_opts:
      type: nfs
      o: addr=192.168.1.6,vers=4,nolock,soft,rw
      device: :/volume1/videos/Anime
  tv:
    driver_opts:
      type: nfs
      o: addr=192.168.1.6,vers=4,nolock,soft,rw
      device: :/volume1/videos/TV Shows
  movies:
    driver_opts:
      type: nfs
      o: addr=192.168.1.6,vers=4,nolock,soft,rw
      device: :/volume1/videos/Movies
networks: {}
