version: "3.8"
services:
  nginx-proxy-manager:
    restart: unless-stopped
    image: jlesage/nginx-proxy-manager
    ports:
      - 80:8080
      - 81:8181
      - 443:4443
    volumes:
      - ./config/npm:/config
  ddclient:
    restart: unless-stopped
    image: linuxserver/ddclient
    volumes:
      - ./config/ddclient/config.conf:/etc/ddclient/ddclient.conf
networks: {}
