---
all:
  children:
    compute_servers:
      hosts:
        max:
          ansible_host: 192.168.1.245
          ansible_user: justin
          server_role: local_llm
          # GPU Config
          gpu_type: nvidia
          gpu_model: rtx_3090
          gpu_count: 2
          docker_gpu: true
          docker_runtime: nvidia
          docker_devices:
            - /dev/nvidia0:/dev/nvidia0
            - /dev/nvidia1:/dev/nvidia1
            - /dev/nvidiactl:/dev/nvidiactl
            - /dev/nvidia-uvm:/dev/nvidia-uvm
        mini:
          ansible_host: 192.168.1.69
          ansible_user: justin
          server_role: compute
          # GPU Config
          gpu_type: intel_arc
          gpu_model: arc_graphics # Core Ultra 7 255H Integrated
          docker_gpu: true
          docker_runtime: runc
          docker_devices:
            - /dev/dri:/dev/dri # Intel Arc + QuickSync
          # Capabilities
          has_npu: true
          npu_tops: 96
          supports_av1_encode: true
        mac:
          ansible_host: 192.168.1.9
          ansible_user: justin
          server_role: deprecated
          # GPU Config
          gpu_type: apple_silicon
          gpu_model: m4
          docker_gpu: false # macOS doesn't support virtualization in containers
          docker_runtime: runc
          deprecated: true
    
    # Stack-based groups (mini server)
    infra_gateway:
      hosts:
        mini:
    
    infra_core:
      hosts:
        mini:
    
    media_acquisition:
      hosts:
        mini:
    
    media_consumption:
      hosts:
        mini:
    
    development:
      hosts:
        mini:
    
    content_management:
      hosts:
        mini:
    
    social:
      hosts:
        mini:
    
    productivity:
      hosts:
        mini:
    
    # Stack-based groups (max server)
    ai:
      hosts:
        max:
    
    infra_periphery:
      hosts:
        max:

  vars:
    ansible_python_interpreter: /usr/bin/python3
