---
- name: Deploy homelab prerequisites
  hosts: compute_servers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Skip deprecated hosts
      meta: end_host
      when: deprecated | default(false)
    - name: Gather facts
      setup:
  roles:
    - prerequisites
    - firewall
    - docker
    - networks
    - docker-volumes
    - security

- name: Install monitoring agent on all devices
  hosts: compute_servers
  roles:
    - monitoring
