---
- name: Restart {{ stack_name }} stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_base_path }}/{{ stack_name }}"
    state: present
    remove_orphans: true
    recreate: always

- name: Reconfigure GitLab if running
  community.docker.docker_container_exec:
    container: gitlab
    command: gitlab-ctl reconfigure
  failed_when: false
