---
- name: Restart Beszel agent Homebrew service
  ansible.builtin.command: brew services restart beszel-agent
  changed_when: true
  when: ansible_facts['os_family'] == 'Darwin'
  listen: Restart Beszel agent
