---
- name: Restart {{ stack_name }} stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_base_path }}/{{ stack_name }}"
    state: present
    remove_orphans: true
    build: always
    recreate: always

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Stop NAS automount before restart
  ansible.builtin.systemd_service:
    name: "{{ nas_systemd_unit_basename }}.automount"
    state: stopped
  listen: Restart NAS automount

- name: Stop NAS mount before restarting automount
  ansible.builtin.systemd_service:
    name: "{{ nas_systemd_unit_basename }}.mount"
    state: stopped
  listen: Restart NAS automount

- name: Start NAS automount after restart
  ansible.builtin.systemd_service:
    name: "{{ nas_systemd_unit_basename }}.automount"
    state: started
    enabled: true
  listen: Restart NAS automount
